name: CI Windows/MSC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v2
    - name: nmake -f Makefile.nmake
      run: cd ./ext/windows-msc && 7z x tools.zip && cd ../.. && nmake -f Makefile.nmake
